name: Continuous Integration
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@10.0
        with:
          lein: 2.9.10
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Setup Python library
        run: pip install lcov_cobertura
      - name: Test
        run: lein cloverage --lcov
      - name: Convert lcov to Cobertura
        run: lcov_cobertura ./target/coverage/lcov.info
      - name: Create report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./coverage.xml
          badge: true
          format: markdown
          output: both
      - name: Add PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
